/**
 * @file contains the icon picker root view.
 * 
 * @typedef { import('../iconconfig').FontAwesomeVersion } FontAwesomeVersion
 * @typedef { import('../iconconfig').CategoryDefinition } CategoryDefinition
 * @typedef { import('../iconconfig').IconDefinition } IconDefinition
 */

import { View, FocusCycler } from 'ckeditor5/src/ui';
import { FocusTracker, KeystrokeHandler } from 'ckeditor5/src/utils';
import { getValidIconStyle } from '../iconutils';
import IconPickerFooter from './iconpickerfooter';
import IconPickerGrid from './iconpickergrid';
import IconPickerHeader from './iconpickerheader';

export default class IconPickerView extends View {
	/**
	 * Creates a new IconPickerView.
	 * 
	 * @param {Locale} locale
	 *   The locale.
	 * @param {FontAwesomeVersion} faVersion
	 *   The version of Font Awesome being used.
	 * @param {Object<string, CategoryDefinition>} faCategories
	 *   The Font Awesome category definitions.
	 * @param {Object<string, IconDefinition>} faIcons
	 *   The Font Awesome icon definitions.
	 */
	constructor(locale, faVersion, faCategories, faIcons) {
		super(locale);

		this.set('categoryName', null);
		this.set('categoryDefinition', null);
		this.set('iconName', null);
		this.set('iconStyle', 'solid');
		this.set('iconDefinition', null);

		const headerView = this.headerView = new IconPickerHeader(locale, faCategories);
		const gridView = this.gridView = new IconPickerGrid(locale);
		const footerView = this.footerView = new IconPickerFooter(locale);

		const items = this.items = this.createCollection();
		const focusTracker = this.focusTracker = new FocusTracker();
		const keystrokes = this.keystrokes = new KeystrokeHandler();

		this._focusCycler = new FocusCycler({
			focusables: items,
			focusTracker: focusTracker,
			keystrokeHandler: keystrokes,
			actions: {
				focusPrevious: 'shift + tab',
				focusNext: 'tab'
			}
		});

		this.setTemplate({
			tag: 'div',
			children: [headerView, gridView, footerView],
			attributes: {
				// Avoid focus loss when the user clicks the area of the grid that is not a button.
				// https://github.com/ckeditor/ckeditor5/pull/12319#issuecomment-1231779819
				tabindex: '-1'
			}
		});

		items.add(headerView.categoryDropdownView.buttonView);
		items.add(gridView);
		items.add(footerView);

		// === Events generated by the different subviews are handled here ===

		// Handles the category change event from the header.
		this.listenTo(headerView, 'execute', (eventInfo, categoryName, categoryDefinition) => {
			this.set('categoryName', categoryName);
			this.set('categoryDefinition', categoryDefinition);
			this.set('iconName', null);
			this.set('iconDefinition', null);
			gridView.refresh(faVersion, faIcons);
			footerView.refresh(faVersion);
		});

		// Handles the icon selection event from the grid.
		this.listenTo(gridView, 'execute', (eventInfo, iconName, iconDefinition) => {
			this.set('iconName', iconName);
			this.set('iconStyle', getValidIconStyle(iconDefinition, this.iconStyle));
			this.set('iconDefinition', iconDefinition);
			footerView.refresh(faVersion);
		});

		// Binds values that need to be avaliable in the different subviews so they remain in sync with the main view.
		headerView.bind('categoryName', 'categoryDefinition').to(this);
		gridView.bind('categoryName', 'categoryDefinition', 'iconName', 'iconStyle').to(this);
		footerView.bind('iconName', 'iconStyle', 'iconDefinition').to(this);

		// Ensures the `execute` event of the icon picker view fires when someone confirms an icon insert.
		footerView.delegate('execute').to(this);
	}

	/**
	 * @inheritdoc
	 */
	render() {
		super.render();

		this.focusTracker.add(this.headerView.categoryDropdownView.buttonView.element);
		this.focusTracker.add(this.gridView.element);
		this.focusTracker.add(this.footerView.formView.element);

		// Start listening for the keystrokes coming from #element.
		this.keystrokes.listenTo(this.element);
	}

	/**
	 * @inheritdoc
	 */
	destroy() {
		super.destroy();

		this.focusTracker.destroy();
		this.keystrokes.destroy();
	}

	/**
	 * Focuses the first focusable in `items`.
	 */
	focus() {
		this.headerView.focus();
	}
}
