/**
 * @file contains the icon picker root view.
 * 
 * @typedef { import('../iconconfig').FontAwesomeVersion } FontAwesomeVersion
 * @typedef { import('../iconconfig').CategoryDefinition } CategoryDefinition
 * @typedef { import('../iconconfig').IconDefinition } IconDefinition
 */

import { View, FocusCycler } from 'ckeditor5/src/ui';
import { FocusTracker, KeystrokeHandler } from 'ckeditor5/src/utils';
import { getValidIconStyle } from '../iconutils';
import IconPickerFooter from './iconpickerfooter';
import IconPickerGrid from './iconpickergrid';
import IconPickerHeader from './iconpickerheader';

export default class IconPickerView extends View {
	/**
	 * Creates a new IconPickerView.
	 * 
	 * @param {Locale} locale
	 *   The locale.
	 * @param {FontAwesomeVersion} faVersion
	 *   The version of Font Awesome being used.
	 * @param {Object<string, CategoryDefinition>} faCategories
	 *   The Font Awesome category definitions.
	 * @param {Object<string, IconDefinition>} faIcons
	 *   The Font Awesome icon definitions.
	 * @param {string[]} faStyles
	 *   The enabled Font Awesome icon styles.
	 */
	constructor(locale, faVersion, faCategories, faIcons, faStyles) {
		super(locale);

		this.set('categoryName', null);
		this.set('categoryDefinition', null);
		this.set('iconName', null);
		this.set('iconStyle', faStyles[0]);
		this.set('iconDefinition', null);

		const headerView = this.headerView = new IconPickerHeader(locale, faCategories);
		const gridView = this.gridView = new IconPickerGrid(locale, faVersion);
		const footerView = this.footerView = new IconPickerFooter(locale, faVersion);

		const items = this.items = this.createCollection();
		const focusTracker = this.focusTracker = new FocusTracker();
		const keystrokes = this.keystrokes = new KeystrokeHandler();

		this._focusCycler = new FocusCycler({
			focusables: items,
			focusTracker: focusTracker,
			keystrokeHandler: keystrokes,
			actions: {
				focusPrevious: 'shift + tab',
				focusNext: 'tab'
			}
		});

		this.setTemplate({
			tag: 'div',
			children: [headerView, gridView, footerView],
			attributes: {
				// Avoid focus loss when the user clicks the area of the grid that is not a button.
				// https://github.com/ckeditor/ckeditor5/pull/12319#issuecomment-1231779819
				tabindex: '-1'
			}
		});

		items.add(headerView.categoryDropdownView.buttonView);

		// === Events generated by the different subviews are handled here. ===

		// Handles the category change event from the header.
		this.listenTo(headerView, 'execute', (eventInfo, categoryName, categoryDefinition) => {
			this.set('categoryName', categoryName);
			this.set('categoryDefinition', categoryDefinition);
			this.set('iconName', null);
			this.set('iconDefinition', null);
			this._startTrackingGrid();
			gridView.refresh(faIcons);
			footerView.refresh(faStyles);
			footerView.set('focusedIconDefinition', null);
			this._stopTrackingFooterForm();
		});

		// Handles the icon selection event from the grid.
		this.listenTo(gridView, 'execute', (eventInfo, iconName, iconDefinition) => {
			this.set('iconName', iconName);
			this.set('iconStyle', getValidIconStyle(iconDefinition, this.iconStyle));
			this.set('iconDefinition', iconDefinition);
			footerView.refresh(faStyles);
			this._startTrackingFooterForm();
		});

		// Handles the icon hover event from the grid.
		this.listenTo(gridView, 'itemHover', (eventInfo, iconName, iconDefinition) => {
			footerView.set('focusedIconDefinition', iconDefinition);
		});

		// Handles the icon focus event from the grid.
		this.listenTo(gridView, 'itemFocus', (eventInfo, iconName, iconDefinition) => {
			footerView.set('focusedIconDefinition', iconDefinition);
		});

		// Tracks the "Show more" button in the grid view.
		this.listenTo(gridView, 'showMorePossible', (eventInfo, value) => {
			if (value)
				this._startTracking(gridView.showMoreButtonView);
			else this._stopTracking(gridView.showMoreButtonView);
		});

		// Handles the icon style change event.
		this.listenTo(footerView, 'changeStyle', (eventInfo, iconStyle) => {
			this.set('iconStyle', iconStyle);
			footerView.refresh(faStyles);
		});

		// Handles the icon insert cancel event.
		this.on('cancel', eventInfo => {
			if (focusTracker.focusedElement == this.footerView.formView.cancelButtonView.element)
				gridView.focus();
			this.set('iconName', null);
			this.set('iconDefinition', null);
			footerView.refresh(faStyles);
			this._stopTrackingFooterForm();
		});

		// Fires the icon insert cancel event if the Escape key is pressed with an icon selected.
		// If an icon is not selected or Escape is pressed twice, the default behavior is to close the icon picker.
		keystrokes.set('Esc', (data, cancel) => {
			if (this.iconName) {
				this.fire('cancel');
				cancel();
			}
		});

		// Binds values that need to be avaliable in the different subviews so they remain in sync with the main view.
		headerView.bind('categoryName', 'categoryDefinition').to(this);
		gridView.bind('categoryName', 'categoryDefinition', 'iconName', 'iconStyle').to(this);
		footerView.bind('iconName', 'iconStyle', 'iconDefinition').to(this);

		// Ensures the `execute` and `cancel` events of the icon picker view fires when someone confirms an icon insert.
		footerView.delegate('execute', 'cancel').to(this);
	}

	/**
	 * Starts tracking a view's focus.
	 * 
	 * @param {View} view
	 *   The view to start tracking.
	 */
	_startTracking(view) {
		if (!this.items.has(view)) {
			this.items.add(view);
			this.focusTracker.add(view.element);
		}
	}

	/**
	 * Stops tracking a view's focus.
	 * 
	 * @param {View} view
	 *   The view to stop tracking.
	 */
	_stopTracking(view) {
		if (this.items.has(view)) {
			this.items.remove(view);
			this.focusTracker.remove(view.element);
		}
	}

	_startTrackingGrid() {
		this._startTracking(this.gridView);
	}

	_startTrackingFooterForm() {
		this._startTracking(this.footerView.formView.styleDropdownView.buttonView);
		this._startTracking(this.footerView.formView.submitButtonView);
		this._startTracking(this.footerView.formView.cancelButtonView);
	}

	_stopTrackingFooterForm() {
		this._startTracking(this.footerView.formView.styleDropdownView.buttonView);
		this._stopTracking(this.footerView.formView.submitButtonView);
		this._stopTracking(this.footerView.formView.cancelButtonView);
	}

	/**
	 * @inheritdoc
	 */
	render() {
		super.render();

		this.focusTracker.add(this.headerView.categoryDropdownView.buttonView.element);

		// Start listening for the keystrokes coming from #element.
		this.keystrokes.listenTo(this.element);
	}

	/**
	 * @inheritdoc
	 */
	destroy() {
		super.destroy();

		this.focusTracker.destroy();
		this.keystrokes.destroy();
	}

	/**
	 * Focuses the first focusable in `items`.
	 */
	focus() {
		this.headerView.focus();
	}
}
